### ISSUE TITLE
Issue running express service

### ISSUE THREAD

**Issue by howardroark** [openops/mom#23]
I'm getting this issue when running the express server.  Might we be missing a package in the `package.json` file?  Could you make a fresh clone of the repo on your Windows machine and see if you get the same issue.

```
Error: Cannot find module 'jade'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at new View (/home/vagrant/domains/mom/node_modules/express/lib/view.js:43:49)
   at Function.app.render (/home/vagrant/domains/mom/node_modules/express/lib/application.js:505:12)
   at ServerResponse.res.render (/home/vagrant/domains/mom/node_modules/express/lib/response.js:826:7)
   at exports.index (/home/vagrant/domains/mom/public/js/routes/index.js:7:7)
   at callbacks (/home/vagrant/domains/mom/node_modules/express/lib/router/index.js:164:37)
   at param (/home/vagrant/domains/mom/node_modules/express/lib/router/index.js:138:11)
```

**Comment by Jordann** [comment]
I just did a fresh clone and ssh'd into the box, I'm having trouble replicating this error.

Although jade is the default templating engine for express, so it should be in the the package.json.

**Comment by howardroark** [comment]
So are you able to load the site?  I should have mentioned that this occurs when requesting the site, not when starting up the express server.

**Comment by Jordann** [comment]
Should be good now in the latest commit. Got rid of the template engine and router.
